export const SozialhilfeConstant = {
  PAGETITLE: 'Sozialhilfe',
  TITLENAVIGATOR: '> Sozialhilfe',
  DETAIL_BEARBEITEN: 'bearbeiten',
  DETAIL_SPEICHERN: 'speichern',
  DETAIL_ABBRECHEN: 'abbrechen',
  DETAIL_LOSCHEN: 'deleteMenuItemTopGrd',
  LIST_EXPORTEXCEL: 'exportExcel',
  LIST_PRINTPDF: 'printPdf',
  LIST_GRIDSETTINGGRIDSETTING: 'GridSettingGridSetting',
  LIST_GRIDSETTING: 'gridSetting',
  LIST_CHOOSERCOLUMN: 'chooserColumn',
  OBJECT: 'object',
  FUNCTION: 'function',
  EQUALS: 'equals',
  CONCURRENCY: 409,
  STATUS_CODE_409001: 409001,
  EVENT_KEY_ARROW_UP: 'ArrowUp',
  EVENT_KEY_ARROW_DOWN: 'ArrowDown',
  UNDEFINED_STRING: 'undefined',
  MAX_LENGHT_STRING_TEXTBOX: 100,
  MIN_LENGHT_STRING: 0,
  SCREEN_RESOLUTION_LARGE: 1500,
};
export const GrundBedarfConstant = {
    BEARBEITEN_BUTTON: 'bearbeiten',
    SPEICHERN_BUTTON: 'speichern',
    ABBRECHEN_BUTTON: 'abbrechen',
    ANPASSUNGI_FURUE_SKOS2005_NUMBER_BOX: 'anpassungI_furUE-SKOS2005',
    ANPASSUNG_FURUE_BERACHNUNGSGRUNDLAGE_NUMBER_BOX: 'anpassung_furUE-Berechnungsgrundlage',
    MONATLICHER_FURUE_BERACHNUNGSGRUNDLAGE_NUMBER_BOX: 'monatlicher_furUE-Berechnungsgrundlage',
    ANPASSUNGI_FURUE_SKOSbzw_NUMBER_BOX: 'anpassungI_furUE-SKOSbzw',
    ANPASSUNGII_FURUE_SKOSbzw_NUMBER_BOX: 'anpassungII_furUE-SKOSbzw',
    NUMBER_FORMAT: '#,##0.00',
    MONATLICHER: 'monatlicher',
    ANPASSUNG_SKOSS2005: 'anpassung-SKOSS2005',
    ANPASSUNG_BERE: 'anpassung-bere',
    ANPASSUNG1_SKOS_BZW: 'anpassung1-SKOSbzw',
    ANPASSUNG2_SKOS_BZW: 'anpassung2-SKOSbzw',
    BG_POSITIONSART_ID_NEBE: 32019,
};
export const VermogenConstant = {
    NEUE_VERMOGEN_BUTTON : 'neue-vermogen',
    BEARBEITEN_BUTTON : 'bearbeiten',
    SPEICHERN_BUTTON : 'speichern',
    ABBRECHEN_BUTTON : 'abbrechen',
};
